export const counties = [
  { value: 'all', label: 'Kõik' },
  { value: 'harju', label: 'Harju' },
  { value: 'hiiu', label: 'Hiiu' },
  { value: 'ida-viru', label: 'Ida-viru' },
  { value: 'jogeva', label: 'Jõgeva' },
  { value: 'jarva', label: 'Järva' },
  { value: 'laane', label: 'Lääne' },
  { value: 'laane_viru', label: 'Lääne-viru' },
  { value: 'polva', label: 'Põlva' },
  { value: 'parnu', label: 'Pärnu' },
  { value: 'rapla', label: 'Rapla' },
  { value: 'saare', label: 'Saare' },
  { value: 'tartu', label: 'Tartu' },
  { value: 'viljandi', label: 'Viljandi' },
  { value: 'voru', label: 'Võru' },
  { value: 'valga', label: 'Valga' },
]
